"""Add Task model and fix Team model

Revision ID: ca8d2f8c9664
Revises: 34c5417e4270
Create Date: 2026-01-13 23:29:13.028895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8d2f8c9664'
down_revision: Union[str, Sequence[str], None] = '34c5417e4270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS priority")
    op.execute("DROP TYPE IF EXISTS status")
    op.execute("DROP TYPE IF EXISTS difficulty")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False, comment='гуид задачи'),
    sa.Column('team_id', sa.Uuid(), nullable=False, comment='гуид команды'),
    sa.Column('task_name', sa.String(), nullable=False, comment='название задачи'),
    sa.Column('task_text', sa.String(), nullable=False, comment='описание задачи'),
    sa.Column('author', sa.Uuid(), nullable=False, comment='Автор задачи'),
    sa.Column('executor', sa.Uuid(), nullable=False, comment='исполнитель задачи'),
    sa.Column('task_update_author', sa.Uuid(), nullable=True, comment='последний редактор задачи'),
    sa.Column('last_executor', sa.Uuid(), nullable=True, comment='предыдущий исполнитель задачи'),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority'), nullable=False, comment='приоритет'),
    sa.Column('status', sa.Enum('is_executor', 'is_not_executor', 'in_progress', 'completed', 'canceled', name='status'), nullable=False, comment='статус задачи'),
    sa.Column('difficulty', sa.Enum('critical_high', 'high', 'medium', 'low', 'unknowed', name='difficulty'), nullable=False, comment='сложность задачи'),
    sa.Column('task_create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='дата создания задачи'),
    sa.Column('task_update_date', sa.DateTime(), nullable=True, comment='текст обнолвения задачи'),
    sa.Column('task_deadline_date', sa.DateTime(), nullable=False, comment='дедлайн задачи'),
    sa.Column('task_finish_date', sa.DateTime(), nullable=False, comment='дата завершения задачи'),
    sa.ForeignKeyConstraint(['author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['executor'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['last_executor'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_update_author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_constraint(op.f('teams_is_chief_key'), 'teams', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('teams_is_chief_key'), 'teams', ['is_chief'], postgresql_nulls_not_distinct=False)
    op.drop_table('tasks')
    # ### end Alembic commands ###
