"""add is_completed field

Revision ID: 833a49e5f6f1
Revises: 2e26abd568dc
Create Date: 2026-01-24 19:23:06.281087

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "833a49e5f6f1"
down_revision: str | Sequence[str] | None = "2e26abd568dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "is_completed",
            sa.Boolean(),
            nullable=True,
            comment="флаг завершенности задачи",
        ),
    )
    op.execute("UPDATE tasks SET is_completed = (status = 'completed')")
    op.alter_column("tasks", "is_completed", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_completed")
    # ### end Alembic commands ###
