"""Add unique constraint to users_to_rooms

Revision ID: 5fc0f7ce67d8
Revises: dedd732c997f
Create Date: 2026-01-23 19:27:37.969122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc0f7ce67d8'
down_revision: Union[str, Sequence[str], None] = 'dedd732c997f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_room', 'users_to_rooms', ['user_id', 'room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_room', 'users_to_rooms', type_='unique')
    # ### end Alembic commands ###
