"""Model UsersToRooms

Revision ID: 8e0e29a3729e
Revises: ca8d2f8c9664
Create Date: 2026-01-22 21:50:45.183308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0e29a3729e'
down_revision: Union[str, Sequence[str], None] = 'ca8d2f8c9664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_to_rooms',
    sa.Column('id', sa.Uuid(), nullable=False, comment='гуид'),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_to_rooms')
    # ### end Alembic commands ###
