"""Add is_chief in model UsersToRooms

Revision ID: 48e8ddc168b3
Revises: f26bdc003d45
Create Date: 2026-01-24 18:47:09.646944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e8ddc168b3'
down_revision: Union[str, Sequence[str], None] = 'f26bdc003d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_to_rooms', sa.Column('is_chief', sa.Boolean(), nullable=False, comment='является ли лидером команды'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_to_rooms', 'is_chief')
    # ### end Alembic commands ###
