"""edit finish_date field

Revision ID: f2052ef58031
Revises: d615f02bd6af
Create Date: 2026-01-24 03:06:56.236137

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2052ef58031'
down_revision: Union[str, Sequence[str], None] = 'd615f02bd6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_finish_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='дата завершения задачи')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_finish_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='дата завершения задачи')
    # ### end Alembic commands ###
