"""edit executor field

Revision ID: 7601865d7874
Revises: 443ee938bb7d
Create Date: 2026-01-24 03:03:08.327384

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7601865d7874"
down_revision: str | Sequence[str] | None = "443ee938bb7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "executor",
        existing_type=sa.UUID(),
        nullable=True,
        existing_comment="исполнитель задачи",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "executor",
        existing_type=sa.UUID(),
        nullable=False,
        existing_comment="исполнитель задачи",
    )
    # ### end Alembic commands ###
