"""Delete list_role_tag

Revision ID: f26bdc003d45
Revises: f2052ef58031
Create Date: 2026-01-24 17:49:48.825557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f26bdc003d45'
down_revision: Union[str, Sequence[str], None] = 'f2052ef58031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'list_tag')
    op.drop_column('rooms', 'list_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('list_role', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='список ролей/должностей'))
    op.add_column('rooms', sa.Column('list_tag', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='список направлений ответственности/сфер'))
    # ### end Alembic commands ###
