"""edit time fields

Revision ID: d615f02bd6af
Revises: 7601865d7874
Create Date: 2026-01-24 03:04:50.842309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd615f02bd6af'
down_revision: Union[str, Sequence[str], None] = '7601865d7874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_create_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='дата создания задачи',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'task_update_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='текст обнолвения задачи',
               existing_nullable=True)
    op.alter_column('tasks', 'task_deadline_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='дедлайн задачи',
               existing_nullable=False)
    op.alter_column('tasks', 'task_finish_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='дата завершения задачи',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_finish_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='дата завершения задачи',
               existing_nullable=False)
    op.alter_column('tasks', 'task_deadline_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='дедлайн задачи',
               existing_nullable=False)
    op.alter_column('tasks', 'task_update_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='текст обнолвения задачи',
               existing_nullable=True)
    op.alter_column('tasks', 'task_create_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='дата создания задачи',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
