"""Add unique constraint to teams: team_id + user_id + room_id

Revision ID: 443ee938bb7d
Revises: 5fc0f7ce67d8
Create Date: 2026-01-23 23:52:49.591261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443ee938bb7d'
down_revision: Union[str, Sequence[str], None] = '5fc0f7ce67d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_team_user_room', 'teams', ['team_id', 'user_id', 'room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_team_user_room', 'teams', type_='unique')
    # ### end Alembic commands ###
