"""Add User, Room, Team model

Revision ID: 34c5417e4270
Revises: 
Create Date: 2026-01-13 20:42:58.603082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c5417e4270'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.Uuid(), nullable=False, comment='гуид комнаты'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='название комнаты'),
    sa.Column('list_role', sa.JSON(), nullable=False, comment='список ролей/должностей'),
    sa.Column('list_tag', sa.JSON(), nullable=False, comment='список направлений ответственности/сфер'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='id пользователя'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='email пользователя'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='имя пользователя'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='фамилия пользователя'),
    sa.Column('patronymic_name', sa.String(length=100), nullable=False, comment='отчество пользователя'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='пароль пользователя'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='флаг удаленности пользователя'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Uuid(), nullable=False, comment='гуид команды'),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False, comment='роль в команде'),
    sa.Column('tag', sa.String(length=100), nullable=False, comment='направление деятельности в команде'),
    sa.Column('is_chief', sa.Boolean(), nullable=False, comment='является ли лидером команды'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('is_chief')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
