"""edit deadline date for task with no deadline

Revision ID: 2e26abd568dc
Revises: f2052ef58031
Create Date: 2026-01-24 16:43:59.460685

"""

from collections.abc import Sequence

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e26abd568dc"
down_revision: str | Sequence[str] | None = "f2052ef58031"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "task_deadline_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_comment="дедлайн задачи",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "task_deadline_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_comment="дедлайн задачи",
    )
    # ### end Alembic commands ###
