"""Add all model

Revision ID: dedd732c997f
Revises: 
Create Date: 2026-01-23 17:25:29.501699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedd732c997f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS priority")
    op.execute("DROP TYPE IF EXISTS status")
    op.execute("DROP TYPE IF EXISTS difficulty")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('room_id', sa.Uuid(), nullable=False, comment='гуид комнаты'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='название комнаты'),
    sa.Column('list_role', sa.JSON(), nullable=False, comment='список ролей/должностей'),
    sa.Column('list_tag', sa.JSON(), nullable=False, comment='список направлений ответственности/сфер'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='id пользователя'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='email пользователя'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='имя пользователя'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='фамилия пользователя'),
    sa.Column('patronymic_name', sa.String(length=100), nullable=False, comment='отчество пользователя'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='пароль пользователя'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='флаг удаленности пользователя'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teams_to_rooms',
    sa.Column('team_id', sa.Uuid(), nullable=False, comment='гуид'),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('users_to_rooms',
    sa.Column('id', sa.Uuid(), nullable=False, comment='гуид'),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False, comment='гуид задачи'),
    sa.Column('team_id', sa.Uuid(), nullable=False, comment='гуид команды'),
    sa.Column('task_name', sa.String(), nullable=False, comment='название задачи'),
    sa.Column('task_text', sa.String(), nullable=False, comment='описание задачи'),
    sa.Column('author', sa.Uuid(), nullable=False, comment='Автор задачи'),
    sa.Column('executor', sa.Uuid(), nullable=False, comment='исполнитель задачи'),
    sa.Column('task_update_author', sa.Uuid(), nullable=True, comment='последний редактор задачи'),
    sa.Column('last_executor', sa.Uuid(), nullable=True, comment='предыдущий исполнитель задачи'),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority'), nullable=False, comment='приоритет'),
    sa.Column('status', sa.Enum('is_executor', 'is_not_executor', 'in_progress', 'completed', 'canceled', name='status'), nullable=False, comment='статус задачи'),
    sa.Column('difficulty', sa.Enum('critical_high', 'high', 'medium', 'low', 'unknowed', name='difficulty'), nullable=False, comment='сложность задачи'),
    sa.Column('task_create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='дата создания задачи'),
    sa.Column('task_update_date', sa.DateTime(), nullable=True, comment='текст обнолвения задачи'),
    sa.Column('task_deadline_date', sa.DateTime(), nullable=False, comment='дедлайн задачи'),
    sa.Column('task_finish_date', sa.DateTime(), nullable=False, comment='дата завершения задачи'),
    sa.ForeignKeyConstraint(['author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['executor'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['last_executor'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_update_author'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams_to_rooms.team_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False, comment='гуид'),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='название команды'),
    sa.Column('role', sa.String(length=100), nullable=False, comment='роль в команде'),
    sa.Column('tag', sa.String(length=100), nullable=False, comment='направление деятельности в команде'),
    sa.Column('is_chief', sa.Boolean(), nullable=False, comment='является ли лидером команды'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams_to_rooms.team_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('tasks')
    op.drop_table('users_to_rooms')
    op.drop_table('teams_to_rooms')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
